name: Publish to PyPI

on:
  release:
    types: [ created ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build
        run: >-
          python -m pip install build

      - name: Run build
        run: >-
          python -m build .

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
